# Generated by Django 5.0 on 2024-10-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_questions_app', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
