# Generated by Django 5.0 on 2024-10-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_questions_app', '0003_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.JSONField(default='None'),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='very good question', max_length=255, unique=True),
        ),
    ]
