# Generated by Django 5.0 on 2024-10-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_questions_app', '0005_alter_question_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(max_length=20),
        ),
    ]
